name: Stack
description: Build, test, and lint a stack-based Haskell project
inputs:
  working-directory:
    description: "Working directory for run commands"
    required: true
    default: .
  stack-yaml:
    description: "Override stack.yaml, relative to working-directory"
    required: true
    default: stack.yaml
  fast:
    description: "Pass --fast in build/test"
    required: true
    default: true
  pedantic:
    description: "Pass --pedantic in build/test"
    required: true
    default: true
  stack-arguments:
    description: "Additional arguments for stack invocations"
    required: true
    default: ''
  hlint:
    description: "Run HLint"
    required: true
    default: true
  weeder:
    description: "Run Weeder"
    required: true
    default: true
outputs: {}
runs:
  using: composite
  steps:
    - id: setup
      name: Setup
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack setup

          if ${{ inputs.hlint }}; then
            stack install --copy-compiler-tool hlint
          fi

          if ${{ inputs.weeder }}; then
            stack install --copy-compiler-tool weeder
          fi

          stack_arguments=()

          if ${{ inputs.fast }}; then
            stack_arguments+=( --fast )
          fi

          if ${{ inputs.pedantic }}; then
            stack_arguments+=( --pedantic )
          fi

          echo "::set-output name=stack-arguments::${stack_arguments[*]}"

    - name: Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal --stack-yaml ${{ inputs.stack-yaml }} \
            build --dependencies-only --test --no-run-tests \
            ${{ inputs.stack-arguments }}

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal --stack-yaml ${{ inputs.stack-yaml }} \
            build ${{ steps.setup.outputs.stack-arguments }} \
            ${{ inputs.stack-arguments }}

    - name: Test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          stack --no-terminal --stack-yaml ${{ inputs.stack-yaml }} \
            build ${{ steps.setup.outputs.stack-arguments }} --test \
            ${{ inputs.stack-arguments }}

    - name: Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          if ${{ inputs.hlint }}; then
            stack exec hlint .
          fi

          if ${{ inputs.weeder }}; then
            stack exec weeder
          fi
