name: CI

on:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version-file: ".nvmrc"
      - run: pnpm install --frozen-lockfile
      - run: pnpm format-check
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm knip
      - run: pnpm coverage
      - run: pnpm build
